# config/settings.yaml
# This file defines brand-specific configurations for different project deployments.

default_config:
  default_preferences:
    name: null # This ensures the onboarding flow is always triggered for the name.
    timezone: null
    language: null
    status: "new"
    morning_muster_time: "09:00"
    evening_reflection_time: "18:00"
    projects: ["general", "work", "personal"]
    ritual_days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"] # Renamed from work_days
    last_morning_trigger_date: ""
    last_evening_trigger_date: ""
  welcome_message_key: "initial_welcome_message"

projects:
  kairo:
    default_preferences:
      name: null # This ensures the onboarding flow is always triggered for the name.
      timezone: null
      language: "he"
      status: "new"
      morning_muster_time: "09:00"
      evening_reflection_time: "18:00"
      projects: ["general", "work", "personal"]
      ritual_days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"] # Renamed from work_days
      last_morning_trigger_date: ""
      last_evening_trigger_date: ""
    welcome_message_key: "initial_welcome_message"

  vlancer_il:
    default_preferences:
      name: null # This ensures the onboarding flow is always triggered for the name.
      timezone: "Asia/Jerusalem"
      language: "he"
      status: "new"
      morning_muster_time: "09:00"
      evening_reflection_time: "18:00"
      projects: ["general", "work", "personal"]
      ritual_days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"] # Renamed from work_days
      last_morning_trigger_date: ""
      last_evening_trigger_date: ""
    welcome_message_key: "vlancer_il_welcome_message"